### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by jamrogers** [BinaryLeo/ESP32_NTPCLOCK#1]
line 141 IPAddress ipNtpServer(129.240.2.6); // Norway Oslo
should read 129,240,2,6 commas not dots

Line 97 should read 
u8g2.drawStr(0, FONT_ONE_HEIGHT * 5, "Waiting for data...");

5 not 4 its covering up the rssi

[https://github.com/BinaryLeo/ESP32_NTPCLOCK/blob/6463475ede00f888d7d16f89e9a0598a2844434c/wifi_kit_32_ntp_clock/wifi_kit_32_ntp_clock.ino#L97C2-L97C63]

**Comment by BinaryLeo** [comment]
thank you @jamrogers. Updating here!
